---
- name: Ensure base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libssl-dev
    - libssl-doc
    - openssh-client
    - openssh-server
    - openssl
    - python3
    - python3-setuptools
    - python3-pip
    - ufw
    - vim

- name: Ensure default editor
  command: update-alternatives --set editor /usr/bin/vim.basic

- name: Ensure sshd config
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Ensure ssh access
  ufw:
    name: OpenSSH
    rule: allow
  notify:
    - restart ufw

- name: Ensure ufw defaults
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - { direction: "outgoing", policy: "allow" }
    - { direction: "incoming", policy: "deny" }
  notify:
    - restart ufw

- name: Ensure ufw rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    src: "{{ item.src }}"
  with_items:
    - { rule: "allow", port: "{{ db_port | default('5432') }}", proto: "tcp", src: "172.30.0.0/16" }
  notify:
    - restart ufw

- name: Enable ufw logging
  ufw:
    logging: on
  notify:
    - restart ufw

- name: Enable ufw
  ufw:
    state: enabled

- name: Ensure pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - asyncpg
